print("Hello World!")
print("This is your first project!")
print("Have a explore and test stuff")
print("We hope you enjoy")
print("\n")
print("The Lintine Foundation")
print("\n")
print("Push <CTRL-R> to run this app")
